In [51]:
import numpy as np
import torch


In [20]:
#x = torch.empty(2, 3)
#x = torch.rand((2, 2), )
#x = torch.zeros((2,2))
#x = torch.ones((2,2), dtype=torch.float32)
x = torch.tensor([2.5, 0.1])


x



tensor([2.5000, 0.1000], dtype=torch.float16)

In [24]:
x = torch.rand((2,2))
y = torch.rand((2,2))

print(x, y, sep="\n")

z = x+y
print(z)

tensor([[0.1309, 0.7620],
        [0.0076, 0.1957]])
tensor([[0.2042, 0.3519],
        [0.5786, 0.9710]])
tensor([[True, True],
        [True, True]])


In [29]:
display(
    torch.add(x, y),
    torch.sub(x, y),
    torch.div(x,y),
)

tensor([[0.3352, 1.1139],
        [0.5862, 1.1667]])

tensor([[-0.0733,  0.4101],
        [-0.5710, -0.7753]])

tensor([[0.6411, 2.1652],
        [0.0131, 0.2015]])

In [36]:
#x = torch.rand((5, 3))

display(
    x,
    x[1],
    x[1, :],
    x[1,1].item(),
)


tensor([[0.8067, 0.5741, 0.2214],
        [0.8021, 0.7221, 0.6468],
        [0.4451, 0.1055, 0.4739],
        [0.5912, 0.7588, 0.9050],
        [0.2775, 0.6399, 0.1725]])

tensor([0.8021, 0.7221, 0.6468])

tensor([0.8021, 0.7221, 0.6468])

0.7221497297286987

In [43]:
x = torch.rand((4, 4))
y = x.view(-1, 8)
y.size(), y


(torch.Size([2, 8]),
 tensor([[0.7669, 0.4311, 0.2418, 0.2316, 0.5222, 0.9808, 0.8330, 0.3550],
         [0.8741, 0.2466, 0.4146, 0.3872, 0.1337, 0.9450, 0.5135, 0.4724]]))

tensor([0.0177, 0.1099, 0.6897, 0.7724, 0.3450, 0.3947, 0.5538, 0.6942, 0.2600,
        0.2309, 0.8313, 0.1837, 0.2239, 0.1700, 0.2723, 0.4918])

In [50]:
a = torch.ones(5)
print(a, type(a))
b = a.numpy()
print(b, type(b))
b += 2
print(a)
print(b)

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [55]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 2
print(a)
print(b)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [58]:
torch.cuda.is_available()

False

In [61]:
torch.device("cuda")

device(type='cuda')

In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y=y.to(device)
  z = x+y
  z = z.to("cpu")

In [62]:
x = torch.ones(5, requires_grad=True)
print(x)



tensor([1., 1., 1., 1., 1.], requires_grad=True)
